monitoring:
  elk:
   enabled: true
elk:
   elasticsearch:
    elasticsearchDataPath: "/var/elk"
    elasticsearchSnapshotPath: "/var/elk/snapshots"
   management:
    fullSnapshotSchedule: "0 0 * * 6"
    dailySnapshotSchedule: "0 * * * *"