---
- name: Turn off swap space
  shell: swapoff -a

- name: Permanently disable swap in /etc/fstab
  replace:
    path: /etc/fstab
    regexp: '^([-_=/a-zA-Z0-9]+\sswap\s+sw.*)$'
    replace: '# \1'
