---
- name: Include distribution specific variables
  include_vars: "{{ item }}"
  with_first_found:
    - files:
        - "{{ ansible_distribution }}-{{ ansible_distribution_version}}.yaml"
        - "{{ ansible_distribution }}-{{ ansible_distribution_major_version}}.yaml"
        - "{{ ansible_distribution }}.yaml"
      paths: ../vars
- name: Include distribution specific install
  include: "{{ item }}"
  with_first_found:
    - "{{ ansible_distribution }}-{{ ansible_distribution_version}}.yaml"
    - "{{ ansible_distribution }}-{{ ansible_distribution_major_version}}.yaml"
    - "{{ ansible_distribution }}.yaml"
  tags: tasks
