---
- name: Install CentOS 7-specific modules-load config
  copy:
    src: modules-load_CentOS-7.conf
    dest: /etc/modules-load.d/30-ericom-shield.conf
    owner: root
    group: root
    mode: 0644

- name: Reload kernel modules
  shell: "systemctl restart systemd-modules-load"

- name: Install CentOS 7-specific sysctl config
  copy:
    src: sysctl_CentOS-7.conf
    dest: /etc/sysctl.d/30-ericom_shield_CentOS-7.conf
    owner: root
    group: root
    mode: 0644

- import_tasks: sysctl_common.yaml
