---
- name: Install sysctl config
  copy:
    src: sysctl_common.conf
    dest: /etc/sysctl.d/30-ericom_shield_common.conf
    owner: root
    group: root
    mode: 0644

- name: Reapply all sysctl parameters
  shell: "systemctl restart systemd-sysctl"
