---
- name: Install the elrepo repository
  yum:
    name:
      - https://www.elrepo.org/elrepo-release-7.0-4.el7.elrepo.noarch.rpm
    state: present

- name: Enable the elrepo-kernel repository
  shell: yum-config-manager --enable elrepo-kernel

- name: Install the latest elrepo kernel
  yum:
    name:
      - kernel-lt
    state: latest
    enablerepo: elrepo-kernel

- name: Set the latest kernel as default
  shell: "grub2-set-default 0"
