version: '3.2'

# Ericom Shield Stack Description
# YML file for Dev

services:
    consul-server:
        image: securebrowsing/shield-configuration:171105-11.20-499
        networks:
             - shield
        deploy:
          mode: replicated
          replicas: 5
          endpoint_mode: dnsrr
          placement:
            constraints:
                - node.labels.management==yes
          update_config:
              parallelism: 1
              failure_action: rollback
              delay: "15s"
          restart_policy:
              condition: any
          resources:
            limits:
              memory: 1GB
              cpus: "1"
        environment:
            - "CONSUL_BIND_INTERFACE=eth0"
            - "NUMBER_OF_EXPECTED=5"

    consul:
        image: securebrowsing/shield-configuration:171105-11.20-499
        networks:
              - shield
        ports:
             - "8500:8500"
        deploy:
          mode: replicated
          replicas: 1
          update_config:
              parallelism: 1
              failure_action: rollback
          restart_policy:
              condition: any
          resources:
            limits:
              memory: 1GB
              cpus: "1"
        environment:
             - "CONSUL_BIND_INTERFACE=eth2"
             - "RUN_AGENT=yes"


volumes:
  elastic:
  portainer:
  admin:

networks:
  shield:
    driver: overlay
    ipam:
      driver: default
      config:
        - subnet: 10.20.0.0/16
