version: '3.2'


services:
  elk:
    image: securebrowsing/shield-elk:latest
    ports:
        - 5601:5601
        - 9200:9200
        - 5014:5014/udp
    networks:
        - shield
    environment:
      - "CONSUL_ADDRESS=consul"
    deploy:
      replicas: 1
      restart_policy:
          condition: any
      placement:
          constraints:
            - node.labels.management==yes
      update_config:
        failure_action: rollback
      resources:
        limits:
          memory: 2GB
          cpus: "1"
    volumes:
        - elastic:/var/lib
  consul:
    image: securebrowsing/shield-configuration:latest
    #user: consul
    networks:
      - shield
    ports:
      - "8500:8500"
    deploy:
      mode: replicated
      replicas: 1
      placement:
        constraints:
          - node.labels.management==yes
      update_config:
        parallelism: 1
        failure_action: rollback
      restart_policy:
        condition: any
      resources:
        limits:
          memory: 1GB
          cpus: "1"
    environment:
      - "CONSUL_BIND_INTERFACE=eth2"
      - "NUMBER_OF_EXPECTED=1"
    logging:
      driver: syslog
      options:
        syslog-address: udp://${SYS_LOG_HOST}:5014

  maintence:
    image: securebrowsing/shield-maintenance:test
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    networks:
      - shield
    deploy:
      mode: global
      restart_policy:
          condition: any
      update_config:
          failure_action: rollback
      resources:
        limits:
          memory: 2GB
          cpus: "1"
    environment:
      - "IMAGE_CLEAN_INTERVAL=1m"
    logging:
      driver: syslog
      options:
        syslog-address: udp://${SYS_LOG_HOST}:5014

volumes:
  elastic:
  portainer:
  admin:

networks:
  shield:
    driver: overlay
    ipam:
      driver: default
      config:
        - subnet: 172.16.0.0/16